# Changes here will be overwritten by Copier
_commit: 2024.11.28
_src_path: gh:zenml-io/template-e2e-batch
data_quality_checks: true
email: ''
full_name: Dominik Ciołczyk
hyperparameters_tuning: true
metric_compare_promotion: true
notify_on_failures: true
notify_on_successes: true
open_source_license: mit
product_name: cloud-resource-prediction
project_name: cloud-resource-prediction
target_environment: staging
version: 0.0.1
zenml_server_url: ''
