RAW_POLCOM_DATA_BASE_PATH = "../data/raw/Dane-Polcom/2022/AGH2022/"

PROCESSED_POLCOM_DATA_BASE_PATH = "../data/processed/Dane-Polcom/"
PROCESSED_POLCOM_DATA_2022_M_PATH = PROCESSED_POLCOM_DATA_BASE_PATH + "2022/M/"
PROCESSED_POLCOM_DATA_2022_Y_PATH = PROCESSED_POLCOM_DATA_2022_M_PATH + "2022/Y/"


PROCESSED_AZURE_DATA_PATH = "../data/processed/azure/"