RAW_DATA_UNZIP_PATH = "../data/raw/"

RAW_POLCOM_DATA_ZIP_PATH = "../data/Dane - Polcom.zip"

RAW_POLCOM_DATA_BASE_PATH = "../data/raw/Dane - Polcom/"
RAW_POLCOM_DATA_2022_PATH = RAW_POLCOM_DATA_BASE_PATH + "2022/AGH2022/"

PROCESSED_POLCOM_DATA_BASE_PATH = "../data/processed/Dane - Polcom/"
PROCESSED_POLCOM_DATA_2022_PATH = PROCESSED_POLCOM_DATA_BASE_PATH + "2022/"
PROCESSED_POLCOM_DATA_2022_M_PATH = PROCESSED_POLCOM_DATA_2022_PATH + "M/"
PROCESSED_POLCOM_DATA_2022_Y_PATH = PROCESSED_POLCOM_DATA_2022_PATH + "Y/"


PROCESSED_AZURE_DATA_PATH = "../data/processed/azure/"